export const questions = [
	'Animal',
	'Country',
	'Dessert',
	'IT Company',
	'Movie',
	'Musician',
	'Amusement Park',
	'Athlete',
	'Band',
	'Fantasy Character',
	'City in the World',
	'Color',
	'Comic Book Character',
	'Comic Book',
	'Singer',
	'Hip Hop Artist',
	'Rapper',
	'Television Show',
	'Video Game',
	'Cosmetic Company',
	'Fast Food Restaurant',
	'Car Brand',
	'Mobile Game',
	'Teenage Movie Star',
	'Startup Company',
	'State in the US',
	'Soccer Player',
	'Basketball Player',
	'Baseball Player',
	'Sports Team',
	'Sports League',
	'Hotel Chain',
	'Beer',
	'Wine',
	'Soda',
	'Soft Drink',
	'Candy',
	'Cereal',
	'Ice Cream',
	'Coffee',
	'Historical Figure',
	'Historical Event in South Korea',
	'Museum'
];
